# Don't print a new line at the start of the prompt
add_newline = true
prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "nodejs",
    "ruby",
    "rust",
    "python",
    "golang",
    "nix_shell",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "character",
]

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are confguring is "character
symbol = "(*'-') <"
# symbol = "❯"     # The "symbol" segment is being set to "➜"
error_symbol = "(*;-;) <"
# error_symbol = "✗"
use_symbol_for_status = true
vicmd_symbol = "❮"
style_success = "bold green"
style_failure = "bold red"

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[directory]
truncation_length = 8
truncate_to_repo = true


# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true  

